p/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from trial import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trial.urls')),
    path('trial/', include('trial.urls')),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='trial/login.html'), name='login'),
    url(r'^settings/myaccount/$', views.myaccount, name='myaccount'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='trial/password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='trial/password_change_done.html'),
        name='password_change_done'),
]

trial/urls.py
from django.urls import path
from . import views
from django.conf.urls import url


urlpatterns = [
    path('', views.index, name='index'),
    path('sem/<student_roll>/<sem>/', views.sem, name='sem'),
    url(r'^marks/', views.test, name='marks')
]

trial/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse
from phone_field import PhoneField
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import AbstractUser

# Create your models here.
#username:amulya pswd:a
#student_username:sai, pswd:project231
select_gender = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Other', 'Other'),
)
select_year =(
    ('1-1','1-1'),
    ('1-2','1-2'),
    ('2-1','2-1'),
    ('2-2','2-2'),
    ('3-1','3-1'),
    ('3-2','3-2'),
    ('4-1','4-1'),
    ('4-2','4-2'),
)
select_credit = (
        ('O(Outstanding)', 'O(Outstanding)'),
        ('A+(Excellent)', 'A+(Excellent)'),
        ('A(Very Good)','A(Very Good)'),
        ('B+(Good)', 'B+(Good)'),
        ('B(Average)', 'B(Average)'),
        ('C(Pass)', 'C(Pass)'),
        ('F(Fail)', 'F(Fail)'),
        ('AB(Absent)', 'AB(Absent)')
    )


class Dept(models.Model):
    dept_id = models.IntegerField(null = False)
    name = models.CharField(primary_key=True, max_length=200)

    def __str__(self):
        return self.name


class Subject(models.Model):
    subject_name = models.CharField(max_length=100)
    subject_code = models.CharField(max_length=20, null=False)
    subject_creation_date = models.DateTimeField(auto_now=False, auto_now_add=True)
    subject_credits = models.IntegerField(null = False, default=2)

    def __str__(self):
        return self.subject_name

    def get_absolute_url(self):
        return reverse('subjects:subject_list')


class Class(models.Model):
    class_id = models.CharField(primary_key='False', max_length=100, null=False)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    section = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse('student_classes:class_list')

    def __str__(self):
        return "%s "%(self.class_id)


class Sem(models.Model):
    year_sem = models.CharField(max_length=8, choices=select_year)
    select_subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    sem_class = models.ForeignKey(Class, on_delete=models.CASCADE, default= '16CSEA')
    def __str__(self):
        return  self.year_sem

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    student_name = models.CharField(max_length=100)
    student_roll = models.CharField(max_length=10, unique=True)
    student_email = models.EmailField()
    student_gender = models.CharField(max_length=8, choices=select_gender)
    student_class = models.ForeignKey(Class, on_delete=models.CASCADE, default=True, null=False)
    student_date_of_birth = models.DateField(default= datetime.now, blank=True)
    student_phone =PhoneField(blank=True, help_text='Contact phone number')
    father_name = models.CharField(max_length=20, null=True)
    mother_name = models.CharField(max_length=20, null=True)
    parent_phone = PhoneField(blank=True, help_text='Contact phone number')
    student_reg = models.DateField(auto_now_add=True, auto_now=False)

    def get_absolute_url(self):
        return reverse('students:student_create')

    def __str__(self):
        return self.student_name


class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)


class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name='topics', on_delete=models.CASCADE)
    starter = models.ForeignKey(User, related_name='topics', on_delete=models.CASCADE)


class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name='posts',on_delete=models.CASCADE)
    updated_by = models.ForeignKey(User, null=True, related_name='+',on_delete=models.CASCADE)


class StudentCourse(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    sem = models.ForeignKey(Sem, on_delete=models.CASCADE)
    cgpa = models.FloatField(default=6.5)

    def __str__(self):
        return "%s Sem-%s " % (self.student, self.sem)
    class Meta:
        ordering = ['sem']

class Marks(models.Model):
    student_sem = models.ForeignKey(StudentCourse, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    marks = models.CharField(choices=select_credit, max_length=20)

    class Meta:
        ordering = ['-student_sem__sem']

trial/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

trial/views.py
from multiprocessing import context

from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

from django.urls import reverse
from django.contrib.auth import authenticate, login
from .models import *
#from django.core.urlresolvers import reverse
from django.contrib.auth import login as auth_login
from django.test import TestCase
from .forms import SignUpForm
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('index')
    else:
        form = SignUpForm()
    return render(request, 'trial/signup.html', {'form': form})

    def test_contains_form(self):
        form = self.response.context.get('form')
        self.assertIsInstance(form, SignUpForm)


class SuccessfulSignUpTests(TestCase):
    def setUp(self):
        url = reverse('signup')
        data = {
            'username': 'john',
            'email': 'john@doe.com',
            'password1': 'abcdef123456',
            'password2': 'abcdef123456'
        }
        self.response = self.client.post(url, data)
        self.home_url = reverse('index')


def sem(request, student_roll, sem):
    board = get_object_or_404(Board)
    print('currebt sem ----------------------------------------------', student_roll , sem)
    sem_marks = Marks.objects.filter(Q(student_sem__student__student_roll=student_roll) & Q(student_sem__sem__year_sem=sem))
    context = {
        'board': board,
        'roll_no':student_roll,
        'sem_marks' :sem_marks
               }
    print
    return render(request, 'trial/sem.html', context )


@login_required
def index(request):
    if request.user.student:
        return render(request, 'trial/home.html')
    return render(request, 'trial/login.html')

def myaccount(request):
    return render(request, 'trial/myaccount.html')


def test(request):
    sem_list = StudentCourse.objects.all()
    print(sem_list,'---------------------------------------------')
    return  render(request, 'trial/marks.html',{'sem_list':sem_list})

templates/includes/form.html
{% load widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}

{% for field in form %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text }}
      </small>
    {% endif %}
  </div>
{% endfor %}

templates/trial/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}JITS{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    {% block stylesheet %}{% endblock %}
  </head>
  <body>
  {% block body %}
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">JITS Home Page</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mainMenu">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.username }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
            <a class="dropdown-item" href="{% url 'myaccount' %}">My account</a>
            <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

  <div class="container">
    <ol class="breadcrumb my-4">
      {% block breadcrumb %}
      {% endblock %}
    </ol>
    {% block content %}
    {% endblock %}
    <ol class="breadcrumb my-4">
    {% block b %}
      {% endblock %}</ol>
  </div>
{% endblock body %}
 <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/trial/base_accounts.html
{% extends 'trial/base_log.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'index' %}">JITS</a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

templates/trial/base_log.html
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}JITS{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    {% block stylesheet %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">JITS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>
    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

templates/trial/home.html
{% extends 'trial/base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Semester Makrs</li>
{% endblock %}

{% block content %}
<h1>hello <a class="nav-link text-capitalize">{{ request.user.student.student_roll }}</a>
</h1>
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Semesters</th>
        <th>Supplies</th>
        <th>Count</th>
        <th>Total CGPA of Sem</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td>
            <a href="{% url 'sem' request.user.student.student_roll '1-1' %}"><h4>1-1 </h4></a>
          </td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
        </tr>
    </tbody>
      <tbody>
        <tr>
          <td>
            <a href="{% url 'sem'  request.user.student.student_roll '1-2' %}"><h4>1-2</h4></a>
          </td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
        </tr>
    </tbody>
      <tbody>
        <tr>
          <td>
            <a href="{% url 'sem' request.user.student.student_roll '2-1' %}"><h4>2-1</h4></a>
          </td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
        </tr>
    </tbody>
      <tbody>
        <tr>
          <td>
            <a href="{% url 'sem' request.user.student.student_roll '2-2' %}"><h4>2-2</h4></a>
          </td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
        </tr>
    </tbody>
      <tbody>
        <tr>
          <td>
            <a href="{% url 'sem' request.user.student.student_roll '3-1' %}"><h4>3-1</h4></a>
          </td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
        </tr>
    </tbody>
      <tbody>
        <tr>
          <td>
            <a href="{% url 'sem' request.user.student.student_roll  '3-2' %}"><h4>3-2</h4></a>
          </td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
        </tr>
    </tbody>
      <tbody>
        <tr>
          <td>
            <a href="{% url 'sem' request.user.student.student_roll '4-1' %}"><h4>4-1</h4></a>
          </td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
        </tr>
    </tbody>
      <tbody>
        <tr>
          <td>
            <a href="{% url 'sem' request.user.student.student_roll '4-2' %}"><h4>4-2</h4></a>
          </td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
        </tr>
    </tbody>
  </table>
{% endblock %}

templates/trial/login.html
{% extends 'trial/base_accounts.html' %}

{% block title %}Login to JITS{% endblock %}


{% block breadcrumb %}
  <li class="breadcrumb-item active">Login </li>
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Log in</h3>

          <form method="post" novalidate>
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          New to Jits? <a href="{% url 'signup' %}">Sign up</a>
        </div>
      </div>
      <div class="text-center py-2">
        <small>
          <a href="#" class="text-muted">Forgot your password?</a>
        </small>
      </div>
    </div>
  </div>
{% endblock %}

templates/trial/marks.html
{% extends 'trial/base.html' %}
    {% load static %}

    {% block content %}
                  <div class="card mb-3">
            <div class="card-header">
              <i class="fas fa-table"></i>
            <b>Marks</b></div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                        <th>Subject_ID</th>
                        <th>Subjects</th>
                        <th>Credit</th>
                        <th>Grade</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for sc in sem_list %}
                    <tr>
                        <td>{{ sc.sem.year_sem }}</td>
                        <td>{{ sc.sem.subject }}</td>
                        {% for m in sc.sem.marks_set.all %}
                            <td>{{ m.marks1 }}</td>
                        {% endfor %}
                    </tr>
                    {% empty %}
                            <p>student has no courses</p>
                    {% endfor %}

                  </tbody>
                </table>
              </div>
            </div>
          </div>


    {% endblock %}

templates/trial/myaccount.html
{% extends 'trial/base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Details</li>
{% endblock %}

{% block content %}
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">Details</th>
      <th scope="col">Details</th>
    </tr>
  </thead>
  <tbody>
  <tr>
      <td>Name</td>
      <td><a>{{ request.user.student.student_name }}</a></td>
    </tr>
    <tr>
    <tr>
      <td>HallTicket No</td>
      <td><a>{{ request.user.student.student_roll }}</a></td>
    </tr>
    <tr>
      <td>Class</td>
      <td><a>{{ request.user.student.student_class }}</a></td>
    </tr>
    <tr>
      <td>Email</td>
      <td><a>{{ request.user.student.student_email }}</a></td>
    </tr>
  <tr>
      <td>Gender</td>
      <td><a>{{ request.user.student.student_gender }}</a></td>
    </tr>
    <tr>
      <td>Student Phone no</td>
      <td><a>{{ request.user.student.student_phone }}</a></td>
    </tr>
  <tr>
      <td>Student Father</td>
      <td><a>{{ request.user.student.father_name }}</a></td>
    </tr>
  <tr>
      <td>Student Mother</td>
      <td><a>{{ request.user.student.mother_name }}</a></td>
    </tr>
    <tr><center>
        <center><td>Parent Phone</td></center>
        <td><a>{{ request.user.student.parent_phone }}</a></td></center>
    </tr>
  </tbody>
</table>
</center>
{% endblock %}

templates/trial/password_change.html
{% extends 'trial/base.html' %}

{% block title %}Change password{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Change password</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/trial/password_change_done.html
{% extends 'trial/base.html' %}

{% block title %}Change password successful{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'password_change' %}">Change password</a></li>
  <li class="breadcrumb-item active">Success</li>
{% endblock %}

{% block content %}
  <div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
  </div>
  <a href="{% url 'home' %}" class="btn btn-secondary">Return to home page</a>
{% endblock %}

templates/trial/sem.html
{% extends 'trial/base.html' %}


{% block breadcrumb %}
  <li class="breadcrumb-item active">Semester Marks</li>
{% endblock %}

{% block content %}
</h1>
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Subject Code</th>
        <th>Subjects</th>
        <th>Credits</th>
        <th>Grade</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
    {% for marks in sem_marks %}
      <tr>
        <td>{{marks.subject.subject_code}}</td>
        <td>{{marks.subject}}</td>
        <td>{{marks.subject.subject_credits}}</td>
        <td>{{marks.marks}}</td>
          {% if marks.marks == "F(Fail)" %}
        <td class="p-3 mb-2 bg-danger text-white"> Failed </td>
          {% else %}
        <td class="p-3 mb-2 bg-success text-white"> passed </td>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}
{% block b %}

  {% endblock %}

templates/trial/signup.html
{% extends 'trial/base_accounts.html' %}

{% load static %}

{% block breadcrumb %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'index' %}">Jyothishmathi Institute Of Technology and Science</a>
    </h1>
    <div class="row justify-content-center">
      <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Sign up</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-primary btn-block">Create an account</button>
            </form>
          </div>
          <div class="card-footer text-muted text-center">
            Already have an account? <a href="{% url 'login' %}">Log in</a>
                      </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}